[package]
name = "gt-connect"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gt-connect"
path = "src/main.rs"

[dependencies]
graphs = { path = "../../crates/graphs" }
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

